<?php
/**
 * Template File
 * This file is only build for classes which implements Toolset_Admin_Notice_Interface
 *
 * @var Toolset_Admin_Notice_Interface $this
 *
 * @since 2.3 First release
 */
echo '<p>' . __( 'This layout uses WordPress Archive Cell.', 'ddl-layouts' ) . '</p>';

echo Toolset_Admin_Notices_Manager::tpl_button_primary(
	__( 'Visit our guide for more information.', 'ddl-layouts' ),
	'https://toolset.com/documentation/legacy-features/toolset-layouts/wordpress-archive-cell/?utm_source=plugin&utm_medium=gui&utm_campaign=layouts',
	true
);
