<?php
/**
 * Template for the forms notifications GUI, trigger section, post forms.
 *
 * @var array $notification Data for the current notification
 * @var string $ii Index for the current notification
 * @var boolean $enableTestMail
 * @var WP_Post $form
 * @var string $form_type Post type of the current edited form
 *
 * @since 2.1
 *
 * @todo Evaluate the error message about trigger event, it does not belong here
 */
$context = isset( $context ) ? $context : array();

$notification = toolset_getarr( $context, 'notification', array() );
$ii = toolset_getarr( $context, 'ii', '__i__' );
$enableTestMail = toolset_getarr( $context, 'enableTestMail', false );
$form = toolset_getarr( $context, 'form' );
$form_type = toolset_getarr( $context, 'form_type' );

$stati = array(
	'basic' => toolset_getnest( $context, array( 'stati', 'basic' ), array() ),
	'native' => toolset_getnest( $context, array( 'stati', 'native' ), array() ),
	'custom' => toolset_getnest( $context, array( 'stati', 'custom' ), array() ),
);
$stati_label = array(
	'native' => toolset_getnest( $context, array( 'stati_label', 'native' ), '' ),
	'custom' => toolset_getnest( $context, array( 'stati_label', 'custom' ), '' ),
);

$notification_status_event = toolset_getnest( $notification, array( 'event', 'post_status' ) );

$template_repository = \CRED_Output_Template_Repository::get_instance();
$renderer = \Toolset_Renderer::get_instance();

$notification_html_name = "_cred[notification][notifications][{$ii}]";
?>
<fieldset class="cred-fieldset cred-notification-fieldset cred-notification-fieldset-trigger">

    <h4>
        <i title="<?php echo esc_attr(__('Please select the notification trigger event', 'wp-cred')); ?>" id="notification_event_required-<?php echo $ii; ?>" class="fa fa-warning" style="display:none;"></i>
        <?php _e( 'Notification e-mail trigger', 'wp-cred' ); ?>
    </h4>

    <?php do_action('cred_admin_notification_notify_event_options_before', $form, array( $ii, "_cred[notification][notifications][$ii][event][type]", $notification['event']['type']), $notification ); ?>

    <p>
        <label class='cred-label'>
            <input data-cred-bind="{
                validate: {
                required: {
                actions: [
                {action: 'validationMessage', domRef: '#notification_event_required-<?php echo $ii; ?>' },
                {action: 'validateSection' }
                ]
                }
                }
                }"
                type='radio'
                class='js-cred-notification-trigger'
                name='<?php echo esc_attr( $notification_html_name ); ?>[event][type]'
                value='form_submit'
                <?php checked( 'form_submit', toolset_getnest( $notification, array( 'event', 'type' ) ) ); ?> />
            <span><?php _e('When submitting the form', 'wp-cred'); ?></span>
        </label>
    </p>
    <p>
        <label class='cred-label'>
            <input data-cred-bind="{
                validate: {
                required: {
                actions: [
                {action: 'validationMessage', domRef: '#notification_event_required-<?php echo $ii; ?>' },
                {action: 'validateSection' }
                ]
                }
                }
                }"
                type='radio'
                class='js-cred-notification-trigger'
                name='<?php echo esc_attr( $notification_html_name ); ?>[event][type]'
                value='post_modified'
                <?php checked( 'post_modified', toolset_getnest( $notification, array( 'event', 'type' ) ) ); ?> />
			<?php
			/* translators: Label for the option to send a notification when a post changes its status to the one selected right afterwards */
			echo esc_html( 'When post status changes to', 'wp-cred' );
			?>
            <select class="cred_when_status_changes"
                name="<?php echo esc_attr( $notification_html_name ); ?>[event][post_status]"
                data-cred-bind="{
                    action: 'enable',
                    condition: '<?php echo esc_attr( $notification_html_name ); ?>[event][type]=post_modified'
				}">
				<optgroup label="<?php echo esc_attr( $stati_label['native'] ); ?>">
					<?php foreach ( $stati['native'] as $value => $text ) { ?>
						<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, $notification_status_event ); ?>><?php echo esc_html( $text ); ?></option>
					<?php } ?>
				</optgroup>
				<?php
				if ( count( $stati['custom'] ) > 0 ) {
				?>
				<optgroup label="<?php echo esc_attr( $stati_label['custom'] ); ?>">
					<?php foreach ( $stati['custom'] as $value => $text ) { ?>
						<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, $notification_status_event ); ?>><?php echo esc_html( $text ); ?></option>
					<?php } ?>
				</optgroup>
				<?php
				}
				?>
            </select>
        </label>
    </p>
	<?php
	/**
	 * Hook to include extra trigger actions for post forms notifications.
	 *
	 * @param WP_Post $form
	 * @param array
	 *   int The index of the current notification.
	 *   string The name of the radio inputs for the trigger options of this notification.
	 *   string The current notification type.
	 * @param array $notification
	 * @deprecated 2.3 Use toolset_forms_post_form_extend_notification_trigger
	 */
	do_action( 'cred_admin_notification_notify_event_options', $form, array( $ii, "_cred[notification][notifications][$ii][event][type]", $notification['event']['type'] ), $notification );
	?>
	<?php
	/**
	 * Hook to include extra trigger actions for post forms notifications.
	 *
	 * @param WP_Post $form
	 * @param int|string $ii The index of the current notification.
	 * @param array $notification
	 * @since 2.3
	 */
	do_action( 'toolset_forms_post_form_extend_notification_trigger', $form, $ii, $notification );
	?>
    <p>
        <label class='cred-label'>
            <input data-cred-bind="{
                validate: {
                required: {
                actions: [
                {action: 'validationMessage', domRef: '#notification_event_required-<?php echo $ii; ?>' },
                {action: 'validateSection' }
                ]
                }
                }
                }"
                type='radio'
                class='js-cred-notification-trigger'
                name='<?php echo esc_attr( $notification_html_name ); ?>[event][type]'
                value='meta_modified'
                <?php checked( 'meta_modified', toolset_getnest( $notification, array( 'event', 'type' ) ) ); ?> />
            <span><?php _e('When custom fields are modified', 'wp-cred'); ?></span>
        </label>
        <span style="display:inline-block;" data-cred-bind="{ action:'show', condition: '<?php echo esc_attr( $notification_html_name ); ?>[event][type]=meta_modified' }">
            <span style="display:inline-block;" class="cred-notification cred-error" data-cred-bind="{ action: 'show', condition: '<?php echo esc_attr( $notification_html_name ); ?>[event][condition]:count=0' }">
                <i class="fa fa-warning"></i>
                <?php _e('You need to add fields to trigger notifications.', 'wp-cred'); ?>
            </span>
        </span>
    </p>

    <div class="cred_notify_event_field_conditions_container" data-cred-bind="{
            action: 'show',
            condition: '<?php echo esc_attr( $notification_html_name ); ?>[event][type]=meta_modified'
            }">
        <p class='cred-explain-text'><?php _e('Additional field conditions:', 'wp-cred'); ?></p>
        <div id="cred_notify_event_field_conditions_container_fields-<?php echo $ii; ?>" class="cred_notify_event_field_conditions_container_fields">
            <?php
            $condition_data = $context;
            foreach ( array_values( $notification['event']['condition'] ) as $jj => $condition ) {
                $condition_data['jj'] = $jj;
                $condition_data['condition'] = $condition;
                $renderer->render(
                    $template_repository->get( \CRED_Output_Template_Repository::NOTIFICATION_EDITOR_SECTION_SHARED_TRIGGER_META_CONDITION ),
                    $condition_data
                );
            }
            ?>
        </div>

        <div data-cred-bind="{
            action: 'show',
            condition: '<?php echo esc_attr( $notification_html_name ); ?>[event][condition]:count>=2'
            }">
            <p>
                <label>
                    <input type="radio"
                        name="<?php echo esc_attr( $notification_html_name ); ?>[event][any_all]"
                        value="ALL"
                        <?php checked( 'ALL', toolset_getnest( $notification, array( 'event', 'any_all' ) ) ); ?>/>
                    <span><?php _e('All are true', 'wp-cred'); ?></span>
                </label>
                <label>
                    <input type="radio"
                        name="<?php echo esc_attr( $notification_html_name ); ?>[event][any_all]"
                        value="ANY"
                        <?php checked( 'ANY', toolset_getnest( $notification, array( 'event', 'any_all' ) ) ); ?>/>
                    <span><?php _e('Any is true', 'wp-cred'); ?></span>
                </label>
            </p>
        </div>

        <a href="javascript:;" data-cred-bind="{
            event: 'click',
            action: 'addItem',
            tmplRef: '#cred_notification_field_condition_template',
            modelRef: '<?php echo esc_attr( $notification_html_name ); ?>[event][condition][__j__]',
            domRef: '#cred_notify_event_field_conditions_container_fields-<?php echo $ii; ?>',
            replace: [
                '__'+'i__',  '<?php echo $ii; ?>',
                '__j__',  { next: '<?php echo esc_attr( $notification_html_name ); ?>[event][condition]'}
            ]
            }"
            class="cred_add_notify_event_field_condition button">
            <?php _e( 'Add condition by field', 'wp-cred' ); ?>
        </a>

    </div>
</fieldset>
