<?php
/**
 * underscore.js template for the dialog alerting the consequences of changing the editor type
 *
 * @since 2.2
 */
?>
<script type="text/html" id="tmpl-cred-editor-scaffold-dialog-switch-to-dd">
	<div class="cred-editor-scaffold-dialog-switch">
		<p><?php esc_html_e( 'Your edits can be lost if you switch back to the visual editor. Are you sure you want to proceed?', 'wp-cred' ); ?></p>
	</div>
</script>
