<?php
/**
 * underscore.js template for the option of the HTML content field.
 *
 * @since 2.2
 */
?>
<script type="text/html" id="tmpl-cred-editor-scaffold-itemOptions-html-content">
	<div class="toolset-shortcode-gui-dialog-item-group js-toolset-shortcode-gui-dialog-item-group">
		<div>
			<div class="toolset-shortcode-gui-attribute-wrapper js-toolset-shortcode-gui-attribute-wrapper js-toolset-shortcode-gui-attribute-wrapper-for-value" data-attribute="value" data-type="html" data-helper="false" data-default="">
				<h3><?php _e( 'Insert HTML content', 'wp-cred' ); ?></h3>
				<textarea class="cred-scaffold-html-content"></textarea>
			</div>
		</div>
	</div>
</script>
