<?php
/**
 * underscore.js template for the options of each item in the dialog to insert a Toolset Form scaffold.
 *
 * @since 2.2
 */
?>
<script type="text/html" id="tmpl-cred-editor-scaffold-itemOptions-conditionals">
	<div class="toolset-shortcode-gui-dialog-item-group js-toolset-shortcode-gui-dialog-item-group">
		<div>
			<div class="toolset-shortcode-gui-attribute-wrapper js-toolset-shortcode-gui-attribute-wrapper js-toolset-shortcode-gui-attribute-wrapper-for-value" data-attribute="conditionals" data-type="conditionals" data-helper="false" data-default="">
				<# print( data.templates.conditionalGroups.gui( {} ) ); #>
			</div>
		</div>
	</div>
</script>
